// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "httpfs/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// PostCallBackFunc is an autogenerated mock type for the PostCallBackFunc type
type PostCallBackFunc struct {
	mock.Mock
}

type PostCallBackFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *PostCallBackFunc) EXPECT() *PostCallBackFunc_Expecter {
	return &PostCallBackFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *PostCallBackFunc) Execute(_a0 context.Context, _a1 entities.Hash) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Hash) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostCallBackFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type PostCallBackFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 entities.Hash
func (_e *PostCallBackFunc_Expecter) Execute(_a0 interface{}, _a1 interface{}) *PostCallBackFunc_Execute_Call {
	return &PostCallBackFunc_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *PostCallBackFunc_Execute_Call) Run(run func(_a0 context.Context, _a1 entities.Hash)) *PostCallBackFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Hash))
	})
	return _c
}

func (_c *PostCallBackFunc_Execute_Call) Return(_a0 error) *PostCallBackFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PostCallBackFunc_Execute_Call) RunAndReturn(run func(context.Context, entities.Hash) error) *PostCallBackFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewPostCallBackFunc creates a new instance of PostCallBackFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostCallBackFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostCallBackFunc {
	mock := &PostCallBackFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
