// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "httpfs/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// PostCallBack is an autogenerated mock type for the PostCallBack type
type PostCallBack struct {
	mock.Mock
}

type PostCallBack_Expecter struct {
	mock *mock.Mock
}

func (_m *PostCallBack) EXPECT() *PostCallBack_Expecter {
	return &PostCallBack_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *PostCallBack) Handle(_a0 context.Context, _a1 entities.Hash) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Hash) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostCallBack_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type PostCallBack_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 entities.Hash
func (_e *PostCallBack_Expecter) Handle(_a0 interface{}, _a1 interface{}) *PostCallBack_Handle_Call {
	return &PostCallBack_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *PostCallBack_Handle_Call) Run(run func(_a0 context.Context, _a1 entities.Hash)) *PostCallBack_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Hash))
	})
	return _c
}

func (_c *PostCallBack_Handle_Call) Return(_a0 error) *PostCallBack_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PostCallBack_Handle_Call) RunAndReturn(run func(context.Context, entities.Hash) error) *PostCallBack_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewPostCallBack creates a new instance of PostCallBack. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostCallBack(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostCallBack {
	mock := &PostCallBack{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
