// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// PreCallBackFunc is an autogenerated mock type for the PreCallBackFunc type
type PreCallBackFunc struct {
	mock.Mock
}

type PreCallBackFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *PreCallBackFunc) EXPECT() *PreCallBackFunc_Expecter {
	return &PreCallBackFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *PreCallBackFunc) Execute(_a0 context.Context, _a1 io.Reader) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreCallBackFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type PreCallBackFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 io.Reader
func (_e *PreCallBackFunc_Expecter) Execute(_a0 interface{}, _a1 interface{}) *PreCallBackFunc_Execute_Call {
	return &PreCallBackFunc_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *PreCallBackFunc_Execute_Call) Run(run func(_a0 context.Context, _a1 io.Reader)) *PreCallBackFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader))
	})
	return _c
}

func (_c *PreCallBackFunc_Execute_Call) Return(_a0 error) *PreCallBackFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PreCallBackFunc_Execute_Call) RunAndReturn(run func(context.Context, io.Reader) error) *PreCallBackFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewPreCallBackFunc creates a new instance of PreCallBackFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPreCallBackFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *PreCallBackFunc {
	mock := &PreCallBackFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
