// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "httpfs/internal/entities"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *Storage) Delete(_a0 context.Context, _a1 entities.Hash) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Hash) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Storage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 entities.Hash
func (_e *Storage_Expecter) Delete(_a0 interface{}, _a1 interface{}) *Storage_Delete_Call {
	return &Storage_Delete_Call{Call: _e.mock.On("Delete", _a0, _a1)}
}

func (_c *Storage_Delete_Call) Run(run func(_a0 context.Context, _a1 entities.Hash)) *Storage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Hash))
	})
	return _c
}

func (_c *Storage_Delete_Call) Return(_a0 error) *Storage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Delete_Call) RunAndReturn(run func(context.Context, entities.Hash) error) *Storage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function with given fields: _a0, _a1, _a2
func (_m *Storage) Download(_a0 context.Context, _a1 entities.Hash, _a2 io.Writer) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Hash, io.Writer) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type Storage_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 entities.Hash
//   - _a2 io.Writer
func (_e *Storage_Expecter) Download(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Storage_Download_Call {
	return &Storage_Download_Call{Call: _e.mock.On("Download", _a0, _a1, _a2)}
}

func (_c *Storage_Download_Call) Run(run func(_a0 context.Context, _a1 entities.Hash, _a2 io.Writer)) *Storage_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Hash), args[2].(io.Writer))
	})
	return _c
}

func (_c *Storage_Download_Call) Return(_a0 error) *Storage_Download_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Download_Call) RunAndReturn(run func(context.Context, entities.Hash, io.Writer) error) *Storage_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: _a0, _a1
func (_m *Storage) Upload(_a0 context.Context, _a1 io.Reader) (entities.Hash, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 entities.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) (entities.Hash, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) entities.Hash); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(entities.Hash)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type Storage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 io.Reader
func (_e *Storage_Expecter) Upload(_a0 interface{}, _a1 interface{}) *Storage_Upload_Call {
	return &Storage_Upload_Call{Call: _e.mock.On("Upload", _a0, _a1)}
}

func (_c *Storage_Upload_Call) Run(run func(_a0 context.Context, _a1 io.Reader)) *Storage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader))
	})
	return _c
}

func (_c *Storage_Upload_Call) Return(_a0 entities.Hash, _a1 error) *Storage_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_Upload_Call) RunAndReturn(run func(context.Context, io.Reader) (entities.Hash, error)) *Storage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
