// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "httpfs/internal/entities"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Uploader is an autogenerated mock type for the Uploader type
type Uploader struct {
	mock.Mock
}

type Uploader_Expecter struct {
	mock *mock.Mock
}

func (_m *Uploader) EXPECT() *Uploader_Expecter {
	return &Uploader_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function with given fields: _a0, _a1
func (_m *Uploader) Upload(_a0 context.Context, _a1 io.Reader) (entities.Hash, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 entities.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) (entities.Hash, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) entities.Hash); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(entities.Hash)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Uploader_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type Uploader_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 io.Reader
func (_e *Uploader_Expecter) Upload(_a0 interface{}, _a1 interface{}) *Uploader_Upload_Call {
	return &Uploader_Upload_Call{Call: _e.mock.On("Upload", _a0, _a1)}
}

func (_c *Uploader_Upload_Call) Run(run func(_a0 context.Context, _a1 io.Reader)) *Uploader_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader))
	})
	return _c
}

func (_c *Uploader_Upload_Call) Return(_a0 entities.Hash, _a1 error) *Uploader_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Uploader_Upload_Call) RunAndReturn(run func(context.Context, io.Reader) (entities.Hash, error)) *Uploader_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewUploader creates a new instance of Uploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUploader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Uploader {
	mock := &Uploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
